#!/bin/bash

stty intr ^i
stty susp ^o
qemu-system-arm \
	-kernel kernel \
	-append "console=ttyAMA0 root=/dev/sda2 rootfstype=ext4 rw" \
	-hda rasbian.img \
	-cpu arm1176 -m 256 \
    -M versatilepb -dtb versatile-pb.dtb \
	-no-reboot \
	-serial stdio \
	-nic user,hostfwd=tcp::5022-:22
