pinanas:
  network:
    # MAC address of PiNana's host network card. Type: string. Example: "01:02:03:04:05:06".
    hmac: "{{ ansible_default_ipv4.macaddress }}"
    # Desired IP address of PiNanas's host. Type: string. Example "192.168.0.1".
    ip: "{{ ansible_default_ipv4.address }}"

    dhcp:
      # Base IP for the network. Type: string. Example: "192.168.0.0".
      base: "{{ ansible_default_ipv4.network }}"

      # Network subnet mask. Type: string. Example: "255.255.255.0".
      subnet: "{{ ansible_default_ipv4.netmask }}"

      # Network gateway. Type: string. Example: "192.168.0.254".
      gateway: "{{ ansible_default_ipv4.gateway }}"

      range:
        __range: "{{ [ ansible_default_ipv4.network, ansible_default_ipv4.netmask ] | join('/') | ansible.netcommon.ipaddr('net') }}"
        # First (included) IP of clients inside the network. Type: string. Example: "192.168.0.16".
        start: "{{ __range | ansible.netcommon.ipaddr('1') | ansible.netcommon.ipaddr('ip') }}"

        # Last (included) IP of clients inside the network. Type: string. Example: "192.168.0.64".
        end: "{{ __range | ansible.netcommon.ipaddr('-1') | ansible.netcommon.ipaddr('ip') }}"

    dns:
      # Upstream DNS servers. Type: list of strings. Example:
      # - 1.1.1.1
      # - 1.0.0.1
      upstreams: "{{ ansible_dns.nameservers }}"
