#!/bin/bash

tty_file=$(mktemp)
function tty_reset () {
    stty $(cat ${tty_file})
    rm -f -- ${tty_file}
}
function tty_save () {
    stty -g > ${tty_file}
    return $?
}
function tty_alter () {
    trap tty_reset EXIT
    echo "SIGINT is ^B"
    stty intr ^b
    echo "SIGTSTP is ^N"
    stty susp ^n
}

tty_save && tty_alter

IMAGE_FILE="${1:-somename-os-*.img}"
qemu-system-arm \
    -kernel kernel \
    -append "console=ttyAMA0 root=/dev/sda2 rootfstype=ext4 rw" \
    -hda ${IMAGE_FILE} \
    -cpu arm1176 -m 256 \
    -M versatilepb -dtb versatile-pb.dtb \
    -no-reboot \
    -nographic \
    -serial mon:stdio \
    -nic user,hostfwd=tcp::5022-:22
